stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$garthigank" -p "$"
    - docker build -t $garthigank/flask-app .
    - docker push $garthigank/flask-app

deploy_infra:
  stage: deploy
  image: hashicorp/terraform:latest
  script:
    - cd terraform
    - terraform init
    - terraform apply -auto-approve
  only:
    - main
